name: "Bicep Static Analysis"

on:
  push:
    branches: [ main ]
  pull_request: 
    branches: [ main ]

jobs:
  build-and-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Check for style and best practices (Linting)
      - name: Bicep Lint
        run: az bicep build --file ./main.bicep

      # Compile to ARM Template
      # This confirms modules, scopes, and parameters are all logically linked.
      - name: Bicep Transpile Check
        run: |
          az bicep build --file ./main.bicep --outfile ./azuredeploy.json