name: "Bicep Pre-flight"

on:
  push:
    branches: [ main ]
  pull_request: 
    branches: [ main ]

permissions:
  id-token: write # Required for requesting the JWT
  contents: read  # Required for actions/checkout

jobs:
  validate:
    runs-on:  ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          # Allows the login to succeed for Tenant-level operations
          allow-no-subscriptions: true

      - name: Bicep Lint
        run: az bicep build --file ./main.bicep

      - name: Azure Pre-flight Validation
        run:  |
          az deployment mg validate \
            --location eastus \
            --template-file ./main.bicep \
            --parameters BasicSubscriptionId=${{ secrets.AZURE_SUBSCRIPTION_ID }} \
                         managementGroupId=${{ secrets.AZURE_MGMT_GROUP_ID }}